Repository virtualcell/vcell, pull requests merged in 2023-11, with the labels that each got.

#1010 add missing fonts from java 17 base Docker image
  docker/build/Dockerfile-admin-dev
  docker/build/Dockerfile-api-dev
  docker/build/Dockerfile-batch-dev
  docker/build/Dockerfile-clientgen-dev
  docker/build/Dockerfile-data-dev
  docker/build/Dockerfile-db-dev
  docker/build/Dockerfile-sched-dev
  docker/build/Dockerfile-submit-dev
  docker/build/Dockerfile-web-dev
Labels: Bug, VCell-7.6.0, VCell-7.5.1, Next Release

#1011 vcfield accepts time as constant expression
  vcell-admin/src/main/java/org/vcell/standalone/VCellClientDevMain.java
  vcell-core/src/main/java/cbit/vcell/field/FieldFunctionArguments.java
  vcell-core/src/main/java/cbit/vcell/simdata/DataSetControllerImpl.java
  vcell-core/src/main/java/cbit/vcell/simdata/SimulationData.java
  vcell-core/src/main/java/cbit/vcell/solvers/FiniteVolumeFileWriter.java
Labels: enhancement

#1013 SpringSaLaD related bug fix, robustness
  vcell-client/src/main/java/cbit/vcell/client/desktop/biomodel/BioModelEditorModelPanel.java
  vcell-core/src/main/java/cbit/vcell/mapping/ReactionRuleSpec.java
Labels: Bug, High Priority, SpringSaLaD, Next Release

#1014 add vcell-su db-create-script to bootstrap oracle/postgresql schema
  oracle.sql
  postgres.sql
  vcell-admin/src/main/java/org/vcell/admin/cli/AdminCLI.java
  vcell-admin/src/main/java/org/vcell/admin/cli/db/DatabaseCreateScriptCommand.java
  vcell-server/src/main/java/cbit/vcell/modeldb/SQLCreateAllTables.java
Labels: enhancement, Next Release

#1025 update user build instructions for vcell and vcell cli
  README.md
  README_BioSim.md
Labels: Bug, User Materials

#1043 Dan ss persist scs
  vcell-core/src/main/java/cbit/vcell/mapping/SiteAttributesSpec.java
  vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
  vcell-core/src/test/java/cbit/vcell/biomodel/SpringSaLaDGoodReactionsTest.java
  vcell-core/src/test/resources/cbit/vcell/biomodel/Spring_application.vcml
  vcell-server/src/main/java/cbit/vcell/modeldb/SimulationContextDbDriver.java
  vcell-server/src/main/java/cbit/vcell/modeldb/SpeciesContextSpecTable.java
Labels: High Priority, SpringSaLaD

#1050 Dan ss rule spec
  vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
  vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
  vcell-core/src/test/java/cbit/vcell/biomodel/SpringSaLaDGoodReactionsTest.java
  vcell-core/src/test/resources/cbit/vcell/biomodel/Spring_application.vcml
Labels: High Priority, SpringSaLaD, testing

#1052 new vcell-services script
  docker/swarm/vcell-services.sh
Labels: Type: enhancement

#1057 Deleted ImageJ file and reference in TOC
  vcell-client/UserDocumentation/originalXML/TOC.xml
  vcell-client/UserDocumentation/originalXML/topics/ch_1/Introduction/ImageJService.xml
Labels: User Materials, ImageJ

#1060 Dan ss math model
  vcell-core/src/main/java/cbit/vcell/export/SpringSaLaDExporter.java
  vcell-core/src/main/java/cbit/vcell/geometry/GeometrySpec.java
  vcell-core/src/main/java/cbit/vcell/mapping/GeometryContext.java
  vcell-core/src/main/java/cbit/vcell/solver/Simulation.java
  vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
Labels: High Priority, SpringSaLaD

#1062 Dan export copy menu
  vcell-client/src/main/java/cbit/vcell/export/gui/ExportMonitorPanel.java
Labels: Type: enhancement, High Priority, VCell-7.5.1, user interface
