Repository virtualcell/vcell, pull requests merged in 2024-03, with the labels that each got.

#1167 Better anchor requirements, inconsistent data strict detection
  vcell-client/src/main/java/cbit/vcell/mapping/gui/MolecularTypeSpecsTableModel.java
  vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
  vcell-core/src/main/java/cbit/vcell/mapping/SiteAttributesSpec.java
  vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
Labels: High Priority, SpringSaLaD

#1176 We use the GeometricRegion to recover the correct size of the ROLE_Size parameter
  vcell-core/src/main/java/cbit/vcell/mapping/LangevinMathMapping.java
Labels: High Priority, SpringSaLaD

#1171 1164 n5 exporter quick bug fixes
  vcell-client/src/main/java/cbit/vcell/client/ClientRequestManager.java
  vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataTableModel.java
  vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataViewer.java
  vcell-client/src/main/java/cbit/vcell/client/desktop/DocumentWindow.java
  vcell-client/src/main/java/cbit/vcell/export/gui/N5SettingsPanel.java
  vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
Labels: Type: Bug

#1195 Dan exporter UI
  vcell-client/src/main/java/cbit/vcell/client/data/ExportedDataViewer.java
  vcell-client/src/main/java/cbit/vcell/client/desktop/DocumentWindow.java
Labels: ImageJ, Next Release, Type: Epic
