Repository virtualcell/vcell, pull requests merged in 2024-02, with the labels that each got.

#1122 S3 use TLS
  docker/swarm/README_zeke_stack_on_linux.md
  docker/swarm/docker-compose-small.yml
  docker/swarm/docker-compose.yml
  docker/swarm/localconfig_mockslurm-not-used.sh
  docker/swarm/localconfig_realslurm_oracle.sh
  docker/swarm/localconfig_realslurm_oracle_zeke.sh
  docker/swarm/localconfig_realslurm_postgres.sh
Labels: Type: enhancement, Security

#1123 Springsalad UI and math parser improvements and bug fixing
  vcell-client/src/main/java/org/vcell/model/springsalad/gui/MolecularStructuresPanel.java
  vcell-core/src/main/java/cbit/vcell/math/LangevinParticleMolecularType.java
Labels: SpringSaLaD

#1130 Persistance of springsalad specific entities
  vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
  vcell-core/src/test/java/cbit/vcell/biomodel/SpringSaLaDGoodReactionsTest.java
  vcell-server/src/main/java/cbit/vcell/modeldb/SimulationContextDbDriver.java
  vcell-server/src/main/java/cbit/vcell/modeldb/SpeciesContextSpecTable.java
  vcell-server/src/test/java/cbit/vcell/modeldb/SpeciesContextSpecTableTest.java
  vcell-server/src/test/resources/cbit/vcell/modeldb/Spring_application.vcml
Labels: SpringSaLaD

#1132 eliminating parasitic sim owner references causing NPE for green button
  vcell-core/src/main/java/org/vcell/solver/langevin/LangevinLngvWriter.java
Labels: SpringSaLaD

#1134 Deploy s3 to swarm stack
  docker/swarm/docker-compose-small.yml
  docker/swarm/docker-compose.yml
  docker/swarm/serverconfig-uch.sh
Labels: Type: Bug, Type: enhancement

#1136 SpeciesContextSpec's compareEqual implementation for SpringSaLaD-specific entities
  vcell-core/src/main/java/cbit/vcell/mapping/MolecularInternalLinkSpec.java
  vcell-core/src/main/java/cbit/vcell/mapping/SpeciesContextSpec.java
Labels: High Priority, SpringSaLaD

#1141 N5 export shared vcell simulations and time set specified
  docker/swarm/localconfig_realslurm_oracle_zeke.sh
  vcell-core/src/main/java/cbit/vcell/export/server/ExportServiceImpl.java
  vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
  vcell-core/src/main/java/cbit/vcell/export/server/N5Specs.java
  vcell-core/src/test/java/cbit/vcell/export/N5ExporterTest.java
Labels: Type: Bug

#1146 Normalize Time Index
  vcell-core/src/main/java/cbit/vcell/export/server/N5Exporter.java
  vcell-core/src/test/java/cbit/vcell/export/N5ExporterTest.java
Labels: Type: Bug

#1158 The is2D flag is always false in this version
  vcell-client/src/main/java/cbit/vcell/mapping/gui/SpeciesContextSpecsTableModel.java
Labels: SpringSaLaD
